package at.ac.tuwien.sepr.groupphase.backend.datagenerator;

public class DataGeneratorConstants {

    private DataGeneratorConstants() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    public static final String[] ITEM_DATA = {
        "All-purpose flour", "Baking powder", "Baking soda", "Bread crumbs",
        "Brown sugar", "Canned beans", "Canned tuna", "Canned tomatoes",
        "Chicken broth", "Chili powder", "Chocolate chips", "Cocoa powder",
        "Coconut milk", "Cornmeal", "Cornstarch", "Dried pasta",
        "Dried beans", "Dried fruit", "Dried herbs", "Dried lentils",
        "Extra virgin olive oil", "Granulated sugar", "Honey", "Instant noodles",
        "Ketchup", "Mayonnaise", "Molasses", "Mustard",
        "Oatmeal", "Olive oil", "Onions", "Pancake mix",
        "Peanut butter", "Popcorn kernels", "Powdered sugar", "Raisins",
        "Red wine vinegar", "Rice", "Rolled oats", "Salt",
        "Soy sauce", "Spaghetti", "Spices", "Stock cubes",
        "Sugar", "Tomato paste", "Tomato sauce", "Vanilla extract",
        "Vegetable oil", "Vinegar", "White rice", "Whole wheat flour",
        "Worcestershire sauce", "Yeast", "Apple cider vinegar", "Balsamic vinegar",
        "Barbecue sauce", "Black beans", "Bouillon cubes", "Brown rice",
        "Canned corn", "Canned fruit", "Canned mushrooms", "Canned peas",
        "Canned soup", "Chickpeas", "Cinnamon", "Cloves",
        "Coconut oil", "Cooking spray", "Corn syrup", "Couscous",
        "Crushed red pepper", "Dijon mustard", "Dried basil", "Dried oregano",
        "Dried parsley", "Dried thyme", "Evaporated milk", "Fish sauce",
        "Garlic powder", "Ginger powder", "Hot sauce", "Italian seasoning",
        "Jelly", "Kidney beans", "Lemon juice", "Lime juice",
        "Maple syrup", "Marinara sauce", "Marjoram", "Milk powder",
        "Nutmeg", "Olives", "Paprika", "Pasta sauce",
        "Peanuts", "Pectin", "Pickles", "Pinto beans",
        "Quinoa", "Red pepper flakes", "Relish", "Salsa",
        "Sesame oil", "Sriracha", "Stevia", "Sun-dried tomatoes",
        "Sweetened condensed milk", "Tahini", "Tapioca pearls", "Tea bags",
        "Tortilla chips", "Vegetable broth", "White vinegar", "Whole grain mustard",
        "Whole milk", "Yellow mustard", "Zaatar", "Agar-agar",
        "Almond flour", "Amaranth", "Anchovy paste", "Anise seeds",
        "Arrowroot powder", "Artichoke hearts", "Asafoetida", "Bamboo shoots",
        "Bay leaves", "Beef broth", "Black olives", "Black-eyed peas",
        "Breadcrumbs", "Buckwheat", "Buttermilk powder", "Canned clams",
        "Canned salmon", "Cardamom", "Carob powder", "Chia seeds",
        "Chipotle peppers", "Chutney", "Cilantro", "Coriander seeds",
        "Couscous", "Crackers", "Cream of tartar", "Currants",
        "Curry powder", "Demerara sugar", "Dill", "Edamame",
        "Farro", "Fennel seeds", "Fenugreek", "Flax seeds",
        "Freekeh", "Garam masala", "Ghee", "Gochujang",
        "Golden syrup", "Granola", "Green beans", "Green chilies",
        "Guava paste", "Hazelnuts", "Hoisin sauce", "Hulled barley",
        "Jasmine rice", "Kamut", "Kelp powder", "Kombu",
        "Lentil flour", "Macadamia nuts", "Millet", "Miso paste",
        "Mustard seeds", "Nutritional yeast", "Palm sugar", "Paneer",
        "Pearl barley", "Pine nuts", "Pomegranate molasses", "Polenta",
        "Poppy seeds", "Pumpkin seeds", "Rice flour", "Rice paper",
        "Rice vinegar", "Roasted red peppers", "Rose water", "Rosemary",
        "Saffron", "Sage", "Sesame seeds", "Shallots",
        "Sherry vinegar", "Sorghum", "Star anise", "Steel-cut oats",
        "Sumac", "Sunflower seeds", "Tamarind paste", "Teff",
        "Textured vegetable protein", "Turmeric", "Udon noodles", "Wasabi",
        "Wheat berries", "Wheat bran", "Wheat germ", "White pepper",
        "Wild rice", "Xanthan gum", "Yeast extract", "Za'atar",
        "All-purpose flour", "Baking powder", "Baking soda", "Sugar",
        "Brown sugar", "Butter", "Olive oil", "Vegetable oil",
        "Salt", "Black pepper", "Eggs", "Milk",
        "Heavy cream", "Sour cream", "Yogurt", "Cheese",
        "Cheddar cheese", "Parmesan cheese", "Mozzarella cheese", "Cream cheese",
        "Garlic", "Onions", "Carrots", "Celery",
        "Bell peppers", "Tomatoes", "Cucumbers", "Lettuce",
        "Spinach", "Broccoli", "Cauliflower", "Potatoes",
        "Sweet potatoes", "Green beans", "Peas", "Corn",
        "Mushrooms", "Zucchini", "Eggplant", "Squash",
        "Apples", "Bananas", "Oranges", "Lemons",
        "Limes", "Berries", "Strawberries", "Blueberries",
        "Raspberries", "Blackberries", "Grapes", "Pineapple",
        "Mango", "Peaches", "Pears", "Plums",
        "Cherries", "Avocado", "Chicken breasts", "Ground beef",
        "Pork chops", "Bacon", "Ham", "Sausages",
        "Shrimp", "Salmon", "Tuna", "Cod",
        "Rice", "Pasta", "Spaghetti", "Macaroni",
        "Quinoa", "Couscous", "Oats", "Bread",
        "Tortillas", "Pita bread", "Bagels", "English muffins",
        "Canned tomatoes", "Tomato sauce", "Tomato paste", "Chicken broth",
        "Beef broth", "Vegetable broth", "Soy sauce", "Worcestershire sauce",
        "Hot sauce", "Ketchup", "Mayonnaise", "Mustard",
        "Barbecue sauce", "Honey", "Maple syrup", "Peanut butter",
        "Jelly", "Jam", "Chocolate chips", "Cocoa powder",
        "Vanilla extract", "Almond extract", "Cinnamon", "Nutmeg",
        "Ginger", "Paprika", "Cumin", "Coriander",
        "Turmeric", "Chili powder", "Cayenne pepper", "Red pepper flakes",
        "Oregano", "Thyme", "Rosemary", "Basil",
        "Parsley", "Dill", "Bay leaves", "Sage",
        "Mint", "Cloves", "Allspice", "Cardamom",
        "Fenugreek", "Star anise", "Tarragon", "Lemongrass",
        "Fish sauce", "Tahini", "Sesame oil", "Coconut milk",
        "Red wine vinegar", "White wine vinegar", "Apple cider vinegar", "Balsamic vinegar",
        "Rice vinegar", "Sherry vinegar", "Capers", "Olives",
        "Pickles", "Sun-dried tomatoes", "Anchovies", "Sardines",
        "Artichokes", "Hearts of palm", "Chickpeas", "Lentils",
        "Kidney beans", "Black beans", "Cannellini beans", "Pinto beans",
        "Nuts", "Almonds", "Walnuts", "Pecans",
        "Cashews", "Pistachios", "Hazelnuts", "Sunflower seeds",
        "Pumpkin seeds", "Chia seeds", "Flax seeds", "Hemp seeds",
        "Coconut flakes", "Breadcrumbs", "Panko breadcrumbs", "Cornstarch",
        "Baking powder", "Baking soda", "Yeast", "Gelatin",
        "Agar-agar", "Corn syrup", "Molasses", "Brown sugar",
        "Powdered sugar", "Confectioners' sugar", "Granulated sugar", "Stevia",
        "Honey", "Maple syrup", "Agave nectar", "Brown rice syrup",
        "Palm sugar", "Coconut sugar", "Lemon zest", "Lime zest",
        "Orange zest", "Ginger root", "Garlic cloves", "Shallots",
        "Scallions", "Green onions", "Leeks", "Fennel",
        "Chives", "Radishes", "Beets", "Turnips",
        "Parsnips", "Rutabaga", "Cabbage", "Kale",
        "Collard greens", "Swiss chard", "Bok choy", "Brussels sprouts",
        "Snow peas", "Sugar snap peas", "Asparagus", "Artichokes",
        "Okra", "Tomatillos", "Jalapenos", "Serrano peppers",
        "Habanero peppers", "Poblano peppers", "Chipotle peppers", "Anaheim peppers",
        "Banana peppers", "Pepperoncini", "Watermelon", "Cantaloupe",
        "Honeydew melon", "Papaya", "Kiwi", "Passion fruit",
        "Dragon fruit", "Star fruit", "Guava", "Lychee",
        "Rambutan", "Persimmon", "Pomegranate", "Dates",
        "Figs", "Prunes", "Apricots", "Cranberries",
        "Currants", "Raisins", "Sultanas", "Dried cherries",
        "Dried blueberries", "Dried strawberries", "Dried pineapple", "Dried mango",
        "Dried bananas", "Dried apples", "Dried pears", "Dried peaches",
        "Dried apricots", "Dried cranberries", "Coconut flakes", "Coconut milk",
        "Coconut oil", "Coconut cream", "Coconut water", "Almond milk",
        "Soy milk", "Rice milk", "Oat milk", "Cashew milk",
        "Hemp milk", "Coconut milk", "Buttermilk", "Cream",
        "Half-and-half", "Evaporated milk", "Condensed milk", "Yogurt",
        "Greek yogurt", "Sour cream", "Cottage cheese", "Ricotta cheese",
        "Mascarpone cheese", "Feta cheese", "Goat cheese", "Blue cheese",
        "Gorgonzola cheese", "Brie cheese", "Camembert cheese", "Havarti cheese",
        "Provolone cheese", "Swiss cheese", "Gruyere cheese", "Manchego cheese",
        "Gouda cheese", "Edam cheese", "Monterey Jack cheese", "Pepper Jack cheese",
        "Colby Jack cheese", "Muenster cheese", "Halloumi cheese", "Paneer",
        "Queso fresco", "Queso blanco", "Cotija cheese", "Parmesan cheese",
        "Pecorino Romano cheese", "Asiago cheese", "Fontina cheese", "Jarlsberg cheese",
        "Stilton cheese", "Roquefort cheese", "Cheddar cheese", "American cheese",
        "Mozzarella cheese", "String cheese", "Cheese curds", "Cream cheese",
        "Neufchâtel cheese", "Boursin cheese", "Gouda cheese", "Edam cheese",
        "Colby cheese", "Colby-Jack cheese", "Cheese whiz", "Velveeta cheese",
        "Mozzarella cheese", "Burrata cheese", "Bocconcini cheese", "Mozzarella cheese",
        "Provolone cheese", "Scamorza cheese", "Fontina cheese", "Parmesan cheese",
        "Grana Padano cheese", "Pecorino Romano cheese", "Ricotta Salata cheese", "Ricotta cheese",
        "Mascarpone cheese", "Gorgonzola cheese", "Dolcelatte cheese", "Taleggio cheese",
        "Asiago cheese", "Feta cheese", "Kefalotyri cheese", "Mizithra cheese",
        "Manouri cheese", "Halloumi cheese", "Paneer cheese", "Queso blanco cheese",
        "Queso fresco cheese", "Cotija cheese", "Oaxaca cheese", "Queso de bola cheese",
        "Requesón cheese", "Sao Jorge cheese", "Tetilla cheese", "Valdeon cheese",
        "Mahon cheese", "Roncal cheese", "Serra da Estrela cheese", "Azeitão cheese",
        "Livarot cheese", "Pont-l'Évêque cheese", "Camembert cheese", "Brie cheese",
        "Munster cheese", "Epoisses cheese", "Vacherin cheese", "Abondance cheese",
        "Beaufort cheese", "Comté cheese", "Reblochon cheese", "Saint-Nectaire cheese",
        "Cantal cheese", "Salers cheese", "Tomme de Savoie cheese", "Fourme d'Ambert cheese",
        "Bleu d'Auvergne cheese", "Roquefort cheese", "Milk", "Chocolate", "Banana", "Butter",
        "Honey", "Egg", "Cheese", "Bread", "Apple", "Orange", "Pear", "Grapes", "Strawberries",
        "Blueberries", "Raspberries", "Tomato", "Cucumber", "Lettuce", "Carrot", "Potato", "Onion", "Garlic",
        "Pepper", "Chicken", "Beef", "Pork", "Fish", "Shrimp",
        "Tofu", "Beans", "Rice", "Pasta", "Bread", "Bagel", "Muffin", "Donut", "Cake", "Pie", "Ice Cream",
        "Yogurt", "Coffee", "Tea", "Juice", "Water", "Soda", "Beer", "Wine", "Whiskey"
    };
    public static final String[] GROUP_NAMES = {
        "Family Expenses", "Roommates", "Household Bills", "Vacation Trip",
        "Weekend Getaway", "Friends Reunion", "Birthday Party", "Wedding Planning",
        "Office Lunch", "Team Outing", "College Friends", "Study Group",
        "Gym Buddies", "Carpool", "Festival Celebration", "Sports Team",
        "Book Club", "Music Band", "Dance Class", "Yoga Group",
        "Photography Club", "Cooking Class", "Art Workshop", "Language Exchange",
        "Travel Buddies", "Adventure Club", "Hiking Group", "Cycling Crew",
        "Pet Lovers", "Gardening Group", "Charity Event", "Community Service",
        "Neighborhood Watch", "Investment Group", "Entrepreneurs Club", "Startup Team",
        "Gaming Squad", "Movie Night", "Dinner Club", "Wine Tasting",
        "Beer Club", "Coffee Enthusiasts", "Baking Group", "Crafting Club",
        "Sewing Circle", "Knitting Group", "Parents Group", "Moms Meetup",
        "Dads Club", "New Parents", "Baby Shower", "Bridal Shower",
        "Bachelor Party", "Bachelorette Party", "Sorority Sisters", "Fraternity Brothers",
        "Alumni Group", "Class Reunion", "Sports Fans", "Football Club",
        "Basketball Team", "Cricket Club", "Soccer Team", "Running Group",
        "Marathon Training", "Triathlon Team", "Swim Club", "Yoga Retreat",
        "Mindfulness Group", "Meditation Circle", "Spiritual Group", "Religious Group",
        "Church Group", "Bible Study", "Prayer Group", "Choir Group",
        "Scout Troop", "Youth Group", "Senior Citizens", "Retirement Community",
        "Book Exchange", "Library Group", "Science Club", "Math Club",
        "Engineering Team", "Coding Bootcamp", "Tech Enthusiasts", "Robotics Club",
        "Astronomy Group", "Environmentalists", "Recycling Group", "Green Living",
        "Zero Waste Group", "Sustainable Living", "Healthy Eating", "Vegan Group",
        "Vegetarian Club", "Fitness Challenge", "Weight Loss Group", "Diet Plan",
        "Nutrition Group", "Wellness Circle", "Holistic Health", "Acupuncture Group",
        "Massage Therapy", "Chiropractic Care", "Physical Therapy", "Occupational Therapy",
        "Speech Therapy", "Counseling Group", "Support Group", "Grief Support",
        "Divorce Support", "AA Meeting", "NA Meeting", "Al-Anon Group",
        "Therapy Group", "Mental Health", "Mindfulness Meditation", "Breathing Exercises",
        "Sleep Improvement", "Dream Analysis", "Lucid Dreaming", "Astrology Group",
        "Tarot Reading", "Palmistry Group", "Psychic Circle", "Metaphysical Group",
        "Wicca Circle", "Pagan Group", "Druid Grove", "Shamanic Circle",
        "Spiritual Awakening", "Kundalini Yoga", "Chakra Healing", "Reiki Group",
        "Energy Healing", "Crystal Healing", "Sound Healing", "Hypnotherapy",
        "Past Life Regression", "Akashic Records", "Mediumship Circle", "Spirit Communication",
        "Animal Communication", "Pet Training", "Dog Walkers", "Cat Lovers",
        "Bird Watchers", "Fish Keepers", "Reptile Enthusiasts", "Horse Riders",
        "Equestrian Club", "Animal Rescue", "Wildlife Conservation", "Nature Lovers",
        "Hiking Trails", "Camping Group", "Outdoor Adventures", "Survival Skills",
        "Bushcraft Group", "Foraging Group", "Hunting Group", "Fishing Club",
        "Boating Club", "Sailing Club", "Kayaking Group", "Canoeing Club",
        "Whitewater Rafting", "Rock Climbing", "Bouldering Group", "Caving Club",
        "Mountain Biking", "Road Cycling", "Motorcycle Club", "Car Enthusiasts",
        "Classic Car Club", "Vintage Car Club", "Supercar Club", "Truck Enthusiasts",
        "Off-Road Club", "4x4 Club", "RV Group", "Camping Caravan",
        "Van Life Group", "Tiny House Community", "Minimalist Living", "Simple Living",
        "Homesteading", "Self-Sufficiency", "Urban Gardening", "Permaculture Group",
        "Organic Farming", "CSA Group", "Farmers Market", "Local Food Movement",
        "Slow Food Movement", "Foodies", "Restaurant Critics", "Wine Connoisseurs",
        "Beer Aficionados", "Whiskey Enthusiasts", "Scotch Lovers", "Cigar Aficionados",
        "Tea Tasting", "Coffee Connoisseurs", "Craft Beer Brewers", "Home Winemakers",
        "Home Distillers", "Fermentation Group", "Cheese Makers", "Bread Bakers",
        "Pastry Chefs", "Chocolatiers", "Candy Makers", "Ice Cream Makers",
        "Pizza Lovers", "BBQ Enthusiasts", "Grill Masters", "Sous Vide Cooking",
        "Molecular Gastronomy", "Sushi Chefs", "Asian Cuisine", "Italian Cuisine",
        "French Cuisine", "Mexican Cuisine", "Indian Cuisine", "Mediterranean Cuisine",
        "Middle Eastern Cuisine", "African Cuisine", "Caribbean Cuisine", "Latin American Cuisine",
        "Fusion Cuisine", "Ethnic Foods", "Gluten-Free Cooking", "Keto Cooking",
        "Paleo Cooking", "Whole30 Group", "Intermittent Fasting", "Vegan Cooking",
        "Vegetarian Cooking", "Raw Food Group", "Juicing Group", "Smoothie Group",
        "Superfoods Group", "Herbal Remedies", "Natural Medicine", "Holistic Nutrition",
        "Alternative Medicine", "Functional Medicine", "Integrative Medicine", "Ayurveda Group",
        "Traditional Chinese Medicine", "Naturopathy Group", "Homeopathy Group", "Biohacking Group",
        "Longevity Group", "Anti-Aging Group", "Wellness Retreats", "Health Coaches",
        "Life Coaches", "Career Coaches", "Business Coaches", "Executive Coaches",
        "Leadership Group", "Management Group", "Entrepreneur Group", "Startup Founders",
        "Angel Investors", "Venture Capitalists", "Business Networking", "Professional Networking",
        "Industry Experts", "Thought Leaders", "Influencers Group", "Social Media Group",
        "Content Creators", "Bloggers Group", "YouTubers Group", "Podcasters Group",
        "TikTok Creators", "Instagram Influencers", "Facebook Group Admins", "LinkedIn Professionals",
        "Twitter Enthusiasts", "Social Media Marketers", "Digital Marketers", "SEO Experts",
        "PPC Specialists", "Email Marketers", "Affiliate Marketers", "E-commerce Group",
        "Dropshipping Group", "Amazon Sellers", "eBay Sellers", "Etsy Sellers",
        "Craft Fair Vendors", "Farmers Market Vendors", "Artisans Group", "Crafters Group",
        "Handmade Items Group", "DIY Projects", "Home Renovation Group", "Interior Design Group",
        "Architecture Group", "Real Estate Investors", "Landlords Group", "Property Managers",
        "Renters Group", "Home Buyers", "First-Time Home Buyers", "House Flippers",
        "Tiny House Builders", "Container Home Builders", "Sustainable Builders", "Green Architects",
        "Passive House Group", "Net-Zero Energy Group", "Off-Grid Living", "Renewable Energy Group",
        "Solar Power Group", "Wind Power Group", "Hydro Power Group", "Geothermal Energy Group",
        "Electric Vehicle Group", "Hybrid Vehicle Group", "Bike Commuters", "Public Transit Group",
        "Car Sharing Group", "Ride Sharing Group", "Urban Explorers", "Street Photographers",
        "Landscape Photographers", "Portrait Photographers", "Wedding Photographers", "Event Photographers",
        "Wildlife Photographers", "Travel Photographers", "Drone Pilots", "Videographers",
        "Filmmakers Group", "Screenwriters Group", "Actors Group", "Stage Crew Group",
        "Theater Group", "Musicians Group", "Composers Group", "Singers Group",
        "Songwriters Group", "Band Members", "Orchestra Members", "Choir Members",
        "Dance Troupes", "Ballet Dancers", "Modern Dancers", "Hip-Hop Dancers",
        "Tap Dancers", "Ballroom Dancers", "Latin Dancers", "Swing Dancers",
        "Folk Dancers", "Square Dancers", "Line Dancers", "Dance Teachers",
        "Dance Students", "Martial Artists", "Karate Group", "Judo Group",
        "Taekwondo Group", "Kung Fu Group", "Aikido Group", "Jiu-Jitsu Group",
        "MMA Group", "Boxing Group", "Kickboxing Group", "Wrestling Group",
        "Fencing Group", "Archery Group", "Shooting Sports Group", "Paintball Group",
        "Airsoft Group", "Laser Tag Group", "Role-Playing Games", "Tabletop Games",
        "Board Games", "Card Games", "Magic: The Gathering", "Dungeons & Dragons",
        "Warhammer 40K", "Cosplay Group", "Anime Fans", "Manga Readers",
        "Comic Book Fans", "Superhero Fans", "Sci-Fi Fans", "Fantasy Fans",
        "Harry Potter Fans", "Star Wars Fans", "Star Trek Fans", "Marvel Fans",
        "DC Comics Fans", "Game of Thrones Fans", "Lord of the Rings Fans", "Horror Movie Fans",
        "Thriller Movie Fans", "Comedy Movie Fans", "Romantic Movie Fans", "Drama Movie Fans",
        "Action Movie Fans", "Adventure Movie Fans", "Documentary Fans", "Independent Film Fans",
        "Classic Film Fans", "Silent Film Fans", "Musical Theater Fans", "Opera Fans",
        "Classical Music Fans", "Jazz Fans", "Blues Fans", "Rock Fans",
        "Metal Fans", "Punk Fans", "Alternative Music Fans", "Indie Music Fans",
        "Pop Music Fans", "Hip-Hop Fans", "Rap Fans", "R&B Fans",
        "Soul Music Fans", "Reggae Fans", "World Music Fans", "Electronic Music Fans",
        "DJ Group", "Producer Group", "Sound Engineers", "Mixing Engineers",
        "Mastering Engineers", "Music Teachers", "Music Students", "Choir Directors",
        "Band Directors", "Orchestra Conductors", "Music Composers", "Music Arrangers",
        "Music Producers", "Songwriters", "Lyricists", "Poets",
        "Novelists", "Short Story Writers", "Essayists", "Journalists",
        "Reporters", "Bloggers", "Content Writers", "Copywriters",
        "Technical Writers", "Grant Writers", "Screenwriters", "Playwrights",
        "Editors", "Proofreaders", "Librarians", "Archivists",
        "Researchers", "Scientists", "Mathematicians", "Engineers",
        "Doctors", "Nurses", "Paramedics", "Firefighters",
        "Police Officers", "Soldiers", "Veterans", "Emergency Responders",
        "Teachers", "Professors", "Tutors", "Trainers",
        "Consultants", "Advisors", "Mentors", "Coaches",
        "Volunteers", "Activists", "Advocates", "Campaigners",
        "Environmentalists", "Humanitarians", "Philanthropists", "Fundraisers",
        "Nonprofit Workers", "Social Workers", "Community Organizers", "Union Members",
        "Trade Unionists", "Labor Organizers", "Political Activists", "Grassroots Organizers",
        "Public Speakers", "Motivational Speakers", "Keynote Speakers", "Conference Attendees",
        "Workshop Attendees", "Seminar Attendees", "Webinar Attendees", "Online Course Students",
        "Distance Learners", "E-Learning Enthusiasts", "MOOC Participants", "Virtual Classroom Students",
        "Language Learners", "ESL Students", "Bilingual Students", "Multilingual Students",
        "Language Exchange Partners", "Study Abroad Students", "International Students", "Foreign Exchange Students",
        "Global Citizens", "World Travelers", "Expatriates", "Immigrants",
        "Refugees", "Asylum Seekers", "Peace Corps Volunteers", "Missionaries",
        "Diplomats", "Ambassadors", "Consuls", "Trade Representatives",
        "Cultural Attachés", "Foreign Service Officers", "International Aid Workers", "Development Workers",
        "Human Rights Advocates", "Legal Aid Workers", "Pro Bono Lawyers", "Public Defenders",
        "Civil Rights Activists", "Labor Rights Activists", "Gender Equality Advocates", "LGBTQ+ Activists"};
}
