package at.ac.tuwien.sepr.groupphase.backend.datagenerator;


import at.ac.tuwien.sepr.groupphase.backend.entity.GroupEntity;
import at.ac.tuwien.sepr.groupphase.backend.entity.Pantry;
import at.ac.tuwien.sepr.groupphase.backend.entity.PantryItem;
import at.ac.tuwien.sepr.groupphase.backend.entity.Unit;
import at.ac.tuwien.sepr.groupphase.backend.repository.GroupRepository;
import at.ac.tuwien.sepr.groupphase.backend.repository.PantryRepository;
import at.ac.tuwien.sepr.groupphase.backend.service.PantryService;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.lang.invoke.MethodHandles;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

@Component
@AllArgsConstructor
public class PantryDataGenerator implements DataGenerator {
    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());


    private final PantryRepository pantryRepository;
    private final GroupRepository groupRepository;
    private final PantryService pantryService;


    @Override
    public void generateData() {
        LOGGER.debug("generating data for pantry");
        List<GroupEntity> groups = groupRepository.findAll();

        List<PantryItem> pantryItems;
        {
            pantryItems = List.of(
                PantryItem.builder().description("Blackberry Jam").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2000).lowerLimit(1000L).build(),
                PantryItem.builder().description("Salt").unit(Unit.Gram).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Pasta").unit(Unit.Gram).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Chocolate").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Tea Bags").unit(Unit.Piece).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Apple").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(3).lowerLimit(4L).build(),
                PantryItem.builder().description("Pine Nuts").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Brown Sugar").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Oatmeal").unit(Unit.Gram).amount(1000).lowerLimit(200L).build(),
                PantryItem.builder().description("Peanuts").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(1500).lowerLimit(null).build(),
                PantryItem.builder().description("Potato").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(800).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(18).lowerLimit(4L).build(),
                PantryItem.builder().description("Black Tea").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2500).lowerLimit(200L).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Yogurt").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(900).lowerLimit(null).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Orange Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Salmon Fillet").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Cheese").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Banana").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Whole Wheat Pasta").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Strawberries").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Spinach").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Butter").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Carrot").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Garlic").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Oatmeal").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Bell Pepper").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Avocado").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salad Dressing").unit(Unit.Milliliter).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Pasta Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Lemons").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Kiwi").unit(Unit.Piece).amount(4).lowerLimit(1L).build(),
                PantryItem.builder().description("Coconut Milk").unit(Unit.Milliliter).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Green Beans").unit(Unit.Gram).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Ground Turkey").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Soy Milk").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Zucchini").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Quinoa").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Limes").unit(Unit.Piece).amount(8).lowerLimit(2L).build(),
                PantryItem.builder().description("Maple Syrup").unit(Unit.Milliliter).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Red Pepper Flakes").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Blueberries").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Celery").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Vanilla Extract").unit(Unit.Milliliter).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Peaches").unit(Unit.Piece).amount(6).lowerLimit(1L).build(),
                PantryItem.builder().description("Almond Milk").unit(Unit.Milliliter).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Chickpeas").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Sesame Oil").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Artichoke Hearts").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Cocoa Powder").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Mushrooms").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Baguette").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Chia Seeds").unit(Unit.Gram).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Breadcrumbs").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Cinnamon").unit(Unit.Gram).amount(50).lowerLimit(10L).build(),
                PantryItem.builder().description("Bell Peppers").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Oregano").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Seeds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Sesame Oil").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Artichoke Hearts").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Cocoa Powder").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Mushrooms").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Baguette").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Chia Seeds").unit(Unit.Gram).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Couscous").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Cranberry Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Yogurt").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Raisins").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Olives").unit(Unit.Gram).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Pine Nuts").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Maple Syrup").unit(Unit.Milliliter).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Quinoa").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Lime").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Balsamic Glaze").unit(Unit.Milliliter).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Coconut Milk").unit(Unit.Milliliter).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Pistachios").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Soy Milk").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Granola").unit(Unit.Gram).amount(600).lowerLimit(100L).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Ginger").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Vanilla Extract").unit(Unit.Milliliter).amount(150).lowerLimit(30L).build(),
                PantryItem.builder().description("Coconut Oil").unit(Unit.Milliliter).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Mixed Nuts").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Oregano").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Blueberries").unit(Unit.Gram).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Red Bell Pepper").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Asparagus").unit(Unit.Piece).amount(10).lowerLimit(3L).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Lentils").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Pineapple Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Sesame Seeds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(1500).lowerLimit(null).build(),
                PantryItem.builder().description("Potato").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(800).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(18).lowerLimit(4L).build(),
                PantryItem.builder().description("Black Tea").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2500).lowerLimit(200L).build(),
                PantryItem.builder().description("Apple").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Yogurt").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(900).lowerLimit(null).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Orange Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Salmon Fillet").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Cheese").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Banana").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Whole Wheat Pasta").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Strawberries").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Spinach").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Butter").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Carrot").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Garlic").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Oatmeal").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Bell Pepper").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Avocado").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salad Dressing").unit(Unit.Milliliter).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Pasta Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Black Beans").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Dijon Mustard").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Artichoke Hearts").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Thyme").unit(Unit.Gram).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Greek Yogurt").unit(Unit.Gram).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Bread Crumbs").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Cinnamon").unit(Unit.Gram).amount(30).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Corn").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Coconut Flakes").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Sunflower Seeds").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Chia Seeds").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Pesto").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Red Pepper Flakes").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Cashews").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Raspberry Jam").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Sour Cream").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Seeds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Sesame Oil").unit(Unit.Milliliter).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Soy Yogurt").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Bagels").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Orange Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Black Pepper").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Pitted Dates").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Tahini").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon Juice").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Breadcrumbs").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Cinnamon").unit(Unit.Gram).amount(50).lowerLimit(10L).build(),
                PantryItem.builder().description("Bell Peppers").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Oregano").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Seeds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato Sauce").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Wheat Flour").unit(Unit.Gram).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Sugar").unit(Unit.Gram).amount(1500).lowerLimit(200L).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Carrots").unit(Unit.Piece).amount(12).lowerLimit(3L).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Apple Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(200L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Bananas").unit(Unit.Piece).amount(8).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Spaghetti").unit(Unit.Gram).amount(900).lowerLimit(100L).build(),
                PantryItem.builder().description("Potatoes").unit(Unit.Piece).amount(10).lowerLimit(2L).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(1200).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(24).lowerLimit(6L).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(2000).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Oranges").unit(Unit.Piece).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(7).lowerLimit(null).build(),
                PantryItem.builder().description("Blackberry Jam").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2000).lowerLimit(null).build(),
                PantryItem.builder().description("Salt").unit(Unit.Gram).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Pasta").unit(Unit.Gram).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(1500).lowerLimit(null).build(),
                PantryItem.builder().description("Potato").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(800).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(18).lowerLimit(4L).build(),
                PantryItem.builder().description("Black Tea").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2500).lowerLimit(200L).build(),
                PantryItem.builder().description("Apple").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Yogurt").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(900).lowerLimit(null).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Orange Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Salmon Fillet").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Cheese").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Banana").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Whole Wheat Pasta").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Strawberries").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Spinach").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Butter").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Carrot").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Garlic").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Oatmeal").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Bell Pepper").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Avocado").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salad Dressing").unit(Unit.Milliliter).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Pasta Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Chocolate").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Tea Bags").unit(Unit.Piece).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(6).lowerLimit(1L).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Coffee").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Green Tea").unit(Unit.Piece).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Red Wine").unit(Unit.Milliliter).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("White Rice").unit(Unit.Gram).amount(1500).lowerLimit(200L).build(),
                PantryItem.builder().description("Honey Mustard").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Grapes").unit(Unit.Gram).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Cherry Tomatoes").unit(Unit.Piece).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Parmesan Cheese").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Cottage Cheese").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Balsamic Vinegar").unit(Unit.Milliliter).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Paprika").unit(Unit.Gram).amount(100).lowerLimit(20L).build(),
                PantryItem.builder().description("Soy Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Frozen Peas").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Mayonnaise").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Bacon").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Corn Tortillas").unit(Unit.Piece).amount(12).lowerLimit(3L).build(),
                PantryItem.builder().description("Pineapple").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salsa").unit(Unit.Gram).amount(200).lowerLimit(50L).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato Sauce").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Wheat Flour").unit(Unit.Gram).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Sugar").unit(Unit.Gram).amount(1500).lowerLimit(200L).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Carrots").unit(Unit.Piece).amount(12).lowerLimit(3L).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Apple Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(200L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Bananas").unit(Unit.Piece).amount(8).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Spaghetti").unit(Unit.Gram).amount(900).lowerLimit(100L).build(),
                PantryItem.builder().description("Potatoes").unit(Unit.Piece).amount(10).lowerLimit(2L).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(1200).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(24).lowerLimit(6L).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(2000).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Oranges").unit(Unit.Piece).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(7).lowerLimit(null).build(),
                PantryItem.builder().description("Blackberry Jam").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2000).lowerLimit(null).build(),
                PantryItem.builder().description("Salt").unit(Unit.Gram).amount(300).lowerLimit(50L).build(),
                PantryItem.builder().description("Pasta").unit(Unit.Gram).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("Chocolate").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Tea Bags").unit(Unit.Piece).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(6).lowerLimit(1L).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Coffee").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Green Tea").unit(Unit.Piece).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Red Wine").unit(Unit.Milliliter).amount(750).lowerLimit(null).build(),
                PantryItem.builder().description("White Rice").unit(Unit.Gram).amount(1500).lowerLimit(200L).build(),
                PantryItem.builder().description("Honey Mustard").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Grapes").unit(Unit.Gram).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Cherry Tomatoes").unit(Unit.Piece).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Parmesan Cheese").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Cottage Cheese").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Balsamic Vinegar").unit(Unit.Milliliter).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Paprika").unit(Unit.Gram).amount(100).lowerLimit(20L).build(),
                PantryItem.builder().description("Soy Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Frozen Peas").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Mayonnaise").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Bacon").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Corn Tortillas").unit(Unit.Piece).amount(12).lowerLimit(3L).build(),
                PantryItem.builder().description("Pineapple").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salsa").unit(Unit.Gram).amount(200).lowerLimit(50L).build(),
                PantryItem.builder().description("Quinoa").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Apple Cider Vinegar").unit(Unit.Milliliter).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Greek Yogurt").unit(Unit.Gram).amount(800).lowerLimit(200L).build(),
                PantryItem.builder().description("Cashews").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Zucchini").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Brown Rice").unit(Unit.Gram).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Maple Syrup").unit(Unit.Milliliter).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Ground Turkey").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Cottage Cheese").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Blueberries").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Cinnamon").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Vanilla Extract").unit(Unit.Milliliter).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Pecans").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("Milk").unit(Unit.Milliliter).amount(1500).lowerLimit(null).build(),
                PantryItem.builder().description("Potato").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Cereal").unit(Unit.Gram).amount(800).lowerLimit(null).build(),
                PantryItem.builder().description("Eggs").unit(Unit.Piece).amount(18).lowerLimit(4L).build(),
                PantryItem.builder().description("Black Tea").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Rice").unit(Unit.Gram).amount(2500).lowerLimit(200L).build(),
                PantryItem.builder().description("Apple").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Bread").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Yogurt").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Chicken Breast").unit(Unit.Gram).amount(900).lowerLimit(null).build(),
                PantryItem.builder().description("Olive Oil").unit(Unit.Milliliter).amount(500).lowerLimit(100L).build(),
                PantryItem.builder().description("Orange Juice").unit(Unit.Milliliter).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Salmon Fillet").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Beans").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Lettuce").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Tomato").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Cheese").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Banana").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Peanut Butter").unit(Unit.Gram).amount(400).lowerLimit(100L).build(),
                PantryItem.builder().description("Honey").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Almonds").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Whole Wheat Pasta").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Strawberries").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Spinach").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Butter").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Carrot").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Onion").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Garlic").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Beef").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Oatmeal").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Lemon").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Cucumber").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Bell Pepper").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Broccoli").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Mango").unit(Unit.Piece).amount(2).lowerLimit(null).build(),
                PantryItem.builder().description("Avocado").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salad Dressing").unit(Unit.Milliliter).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Canned Tuna").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Pasta Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Lime").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Coconut Milk").unit(Unit.Milliliter).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Ginger").unit(Unit.Gram).amount(80).lowerLimit(null).build(),
                PantryItem.builder().description("Green Beans").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Chickpeas").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Coconut Oil").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Cocoa Powder").unit(Unit.Gram).amount(200).lowerLimit(50L).build(),
                PantryItem.builder().description("Red Pepper Flakes").unit(Unit.Gram).amount(30).lowerLimit(null).build(),
                PantryItem.builder().description("Pears").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Baking Powder").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Seeds").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Mustard").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Cilantro").unit(Unit.Gram).amount(30).lowerLimit(null).build(),
                PantryItem.builder().description("Tahini").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Asparagus").unit(Unit.Piece).amount(8).lowerLimit(null).build(),
                PantryItem.builder().description("Rosemary").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Artichoke Hearts").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Oregano").unit(Unit.Gram).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Puree").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Chicken").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Walnuts").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Mint Leaves").unit(Unit.Gram).amount(25).lowerLimit(null).build(),
                PantryItem.builder().description("Cranberries").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Sesame Seeds").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Basil").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Hummus").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Sour Cream").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Papaya").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Shredded Coconut").unit(Unit.Gram).amount(150).lowerLimit(null).build(),
                PantryItem.builder().description("Thyme").unit(Unit.Gram).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Black Beans").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Soy Milk").unit(Unit.Milliliter).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Rosemary").unit(Unit.Gram).amount(20).lowerLimit(null).build(),
                PantryItem.builder().description("Artichoke Hearts").unit(Unit.Piece).amount(6).lowerLimit(null).build(),
                PantryItem.builder().description("Oregano").unit(Unit.Gram).amount(15).lowerLimit(null).build(),
                PantryItem.builder().description("Pumpkin Puree").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Ground Chicken").unit(Unit.Gram).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Cashews").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Zucchini").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Brown Rice").unit(Unit.Gram).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Maple Syrup").unit(Unit.Milliliter).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Ground Turkey").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Cottage Cheese").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Blueberries").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Cinnamon").unit(Unit.Gram).amount(50).lowerLimit(null).build(),
                PantryItem.builder().description("Vanilla Extract").unit(Unit.Milliliter).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Pecans").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("Lime").unit(Unit.Piece).amount(3).lowerLimit(null).build(),
                PantryItem.builder().description("Coconut Milk").unit(Unit.Milliliter).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Ginger").unit(Unit.Gram).amount(80).lowerLimit(null).build(),
                PantryItem.builder().description("Green Beans").unit(Unit.Gram).amount(250).lowerLimit(null).build(),
                PantryItem.builder().description("Chickpeas").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Tofu").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Coconut Oil").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Cocoa Powder").unit(Unit.Gram).amount(200).lowerLimit(50L).build(),
                PantryItem.builder().description("Red Pepper Flakes").unit(Unit.Gram).amount(30).lowerLimit(null).build(),
                PantryItem.builder().description("Pears").unit(Unit.Piece).amount(4).lowerLimit(null).build(),
                PantryItem.builder().description("Capers").unit(Unit.Gram).amount(100).lowerLimit(null).build(),
                PantryItem.builder().description("Baking Powder").unit(Unit.Gram).amount(150).lowerLimit(50L).build(),
                PantryItem.builder().description("White Vinegar").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Paprika").unit(Unit.Gram).amount(100).lowerLimit(20L).build(),
                PantryItem.builder().description("Soy Sauce").unit(Unit.Milliliter).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Frozen Peas").unit(Unit.Gram).amount(400).lowerLimit(null).build(),
                PantryItem.builder().description("Mayonnaise").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Bacon").unit(Unit.Gram).amount(350).lowerLimit(null).build(),
                PantryItem.builder().description("Corn Tortillas").unit(Unit.Piece).amount(12).lowerLimit(3L).build(),
                PantryItem.builder().description("Pineapple").unit(Unit.Piece).amount(1).lowerLimit(null).build(),
                PantryItem.builder().description("Salsa").unit(Unit.Gram).amount(200).lowerLimit(50L).build(),
                PantryItem.builder().description("Quinoa").unit(Unit.Gram).amount(300).lowerLimit(null).build(),
                PantryItem.builder().description("Apple Cider Vinegar").unit(Unit.Milliliter).amount(500).lowerLimit(null).build(),
                PantryItem.builder().description("Greek Yogurt").unit(Unit.Gram).amount(800).lowerLimit(200L).build(),
                PantryItem.builder().description("Cashews").unit(Unit.Gram).amount(200).lowerLimit(null).build(),
                PantryItem.builder().description("Zucchini").unit(Unit.Piece).amount(5).lowerLimit(null).build(),
                PantryItem.builder().description("Brown Rice").unit(Unit.Gram).amount(1000).lowerLimit(null).build(),
                PantryItem.builder().description("Maple Syrup").unit(Unit.Milliliter).amount(250).lowerLimit(50L).build(),
                PantryItem.builder().description("Ground Turkey").unit(Unit.Gram).amount(600).lowerLimit(null).build(),
                PantryItem.builder().description("Cottage Cheese").unit(Unit.Gram).amount(400).lowerLimit(null).build()
            );
        }
        int itemsPerPantry = pantryItems.size() / groups.size();

        int listIndex = 0;
        for (GroupEntity group : groups) {
            Pantry pantry = Pantry.builder()
                .group(group)
                .build();
            pantry.setGroup(group);
            group.setPantry(pantry);
            group = groupRepository.save(group); //save to generate id

            pantry = pantryRepository.getReferenceById(group.getId());
            for (int i = 0; i < itemsPerPantry; i++) {
                //pantry.addItem((pantryItems.get(i + listIndex)));
                pantryService.addItemToPantry(pantryItems.get(listIndex), pantry.getId());
                listIndex++;
            }
            groupRepository.save(group); //save changes
        }

        // For the demo showcase

        long chippinId = groupRepository.findByGroupName("Chippin").getPantry().getId();
        pantryService.addItemToPantry(PantryItem.builder().description("Currypowder").amount(30).unit(Unit.Gram).lowerLimit(null).build(), chippinId);
        pantryService.addItemToPantry(PantryItem.builder().description("Coconut Milk").amount(300).unit(Unit.Milliliter).lowerLimit(250L).build(), chippinId);
        pantryService.addItemToPantry(PantryItem.builder().description("Vegetable Mix").amount(1).unit(Unit.Piece).lowerLimit(null).build(), chippinId);
        pantryService.addItemToPantry(PantryItem.builder().description("Cumin").amount(30).unit(Unit.Gram).lowerLimit(null).build(), chippinId);
        pantryService.addItemToPantry(PantryItem.builder().description("Curcuma").amount(30).unit(Unit.Gram).lowerLimit(null).build(), chippinId);

        groupRepository.save(groupRepository.findByGroupName("Chippin"));
    }

    @Override
    public void cleanData() {
        LOGGER.debug("cleaning data for pantry");
        pantryRepository.deleteAll();
    }

}
